# If validation fails, gradle:generateApi fails claiming this file does not exist.
# For separate validation (with some false positives), do:
#     ./project.rb validate-swagger
swagger: '2.0'
info:
  version: "0.1.0"
  title: "AllOfUs Public API"
  description: "The API for the AllOfUs data browser and public storefront."
  termsOfService: "http://www.pmi-ops.org/terms_of_service.html"
  contact:
    name: "developer_help@pmi-ops.org"
  license:
    name: "MIT"
host: "public-api.pmi-ops.org"
schemes:
  - "https"
produces:
  - "application/json"

# Throughout, we use integer/int64 in preference to string/date-time because Swagger's
# date formatting is inconsistent between server and client. Time values are stored as
# milliseconds since the UNIX epoch.

##########################################################################################
## PATHS
##########################################################################################

paths:

  # Data Browser #######################################################################
  /v1/databrowser/question-analyses:
    get:
      security: []
      tags:
        - dataBrowser

      description: Gets list of analysis and results by analysis id and question concept id
      operationId: "getQuestionAnalyses"
      parameters:
        - in: query
          name: survey_concept_id
          type: string
          format: int64
          required: true
          description: survey concept id
        - in: query
          name: question_concept_id
          type: string
          required: false
          description: question concept id
      responses:
        200:
          description: List of all analyses with results
          schema:
            $ref: "#/definitions/AnalysisListResponse"

  /v1/databrowser/survey-results:
    get:
      security: []
      tags:
        - dataBrowser

      description: Gets list of quetions with results for a survey
      operationId: "getSurveyResults"
      parameters:
        - in: query
          name: survey_concept_id
          type: string
          required: true
          description: survey concept id
      responses:
        200:
          description: A collection of survey modules
          schema:
            $ref: "#/definitions/QuestionConceptListResponse"

  /v1/databrowser/search-concepts:
    get:
      security: []
      tags:
        - dataBrowser

      description: Searches for concepts in concept table with search string and filters
      operationId: "getConceptsSearch"
      parameters:
        - in: query
          name: concept_name
          type: string
          required: false
          description: concept name search string
        - in: query
          name: standard_concept
          type: string
          required: false
          description: standard concept filter
        - in: query
          name: concept_code
          type: string
          required: false
          description: concept code  filter
        - in: query
          name: vocabulary_id
          type: string
          required: false
          description: vocabulary id filter
        - in: query
          name: domain_id
          type: string
          required: false
          description: vocabulary id filter
      responses:
        200:
          description: A collection of concepts
          schema:
            $ref: "#/definitions/ConceptListResponse"

  /v1/databrowser/analysis-results:
    get:
      security: []
      tags:
        - dataBrowser

      description: Gets results for an analysis id and stratum
      operationId: "getAnalysisResults"
      parameters:
        - in: query
          name: analysis_id
          type: integer
          format: int64
          required: true
          description: analysis_id
        - in: query
          name: stratum_1
          type: string
          required: false
          description: stratum 1
        - in: query
          name: stratum_2
          type: string
          required: false
          description: stratum 2
      responses:
        200:
          description: A collection of analysis results from achilles_results_view
          schema:
            $ref: "#/definitions/AnalysisResultListResponse"

  /v1/databrowser/analyses:
    get:
      security: []
      tags:
        - dataBrowser

      description: Gets list of analysis definitions
      operationId: "getAnalyses"
      parameters: []
      responses:
        200:
          description: A collection of analysis definitions
          schema:
            $ref: "#/definitions/AnalysisListResponse"

  /v1/databrowser/participant-count:
    get:
      security: []
      tags:
        - dataBrowser

      description: Gets results for an analysis id and stratum
      operationId: "getParticipantCount"
      parameters: []
      responses:
        200:
          description: A collection of analysis results from achilles_results_view
          schema:
            $ref: "#/definitions/AnalysisResult"

  /v1/databrowser/concept-count:
    get:
      security: []
      tags:
        - dataBrowser

      description: Gets count for concept
      operationId: "getConceptCount"
      parameters:
       - in: query
         name: concept_id
         type: string
         required: true
         description: concept id to get count for
      responses:
        200:
          description: A collection with concept count for concept id
          schema:
            $ref: "#/definitions/AnalysisResultListResponse"

  /v1/databrowser/concept-count-by-gender:
    get:
      security: []
      tags:
        - dataBrowser

      description: Gets counts for concept by gender
      operationId: "getConceptCountByGender"
      parameters:
       - in: query
         name: concept_id
         type: string
         required: true
         description: concept id to get count for
      responses:
        200:
          description: A collection with count for concept by gender
          schema:
            $ref: "#/definitions/AnalysisResultListResponse"

  /v1/databrowser/concept-count-by-age:
    get:
      security: []
      tags:
        - dataBrowser

      description: Gets counts for concept by age
      operationId: "getConceptCountByAge"
      parameters:
       - in: query
         name: concept_id
         type: string
         required: true
         description: concept id to get count for
      responses:
        200:
          description: A collection with count for concept by age decile
          schema:
            $ref: "#/definitions/AnalysisResultListResponse"

  /v1/databrowser/db-domains:
    get:
      security: []
      tags:
        - dataBrowser

      description: Gets list of analysis definitions
      operationId: "getDbDomains"
      parameters: []
      responses:
        200:
          description: A collection of databrowser domains
          schema:
            $ref: "#/definitions/DbDomainListResponse"



  /v1/databrowser/survey-list:
      get:
        security: []
        tags:
          - dataBrowser

        description: Gets list of survey modules
        operationId: "getSurveyList"
        parameters: []
        responses:
          200:
            description: A collection of survey modules
            schema:
              $ref: "#/definitions/DbDomainListResponse"

  /v1/databrowser/child-concepts:
    get:
      security: []
      tags:
        - dataBrowser

      description: Get children of the given concept
      operationId: "getChildConcepts"
      parameters:
        - in: query
          name: concept_id
          type: integer
          format: int64
          required: true
          description: concept id to get maps to concepts
      responses:
        200:
          description: a collection of concepts
          schema:
            $ref: "#/definitions/ConceptListResponse"

  /v1/databrowser/parent-concepts:
      get:
        security: []
        tags:
          - dataBrowser

        description: Gets parent concepts for the given concept
        operationId: "getParentConcepts"
        parameters:
          - in: query
            name: concept_id
            type: integer
            format: int64
            required: true
            description: concept id to get maps to concepts
        responses:
          200:
            description: A collection of databrowser domains
            schema:
              $ref: "#/definitions/ConceptListResponse"



##########################################################################################
## DEFINITIONS
##########################################################################################
definitions:
  Concept:
    type: object
    required:
      - conceptId
      - conceptName
      - domainId
      - vocabularyId
      - conceptCode
      - conceptClassId
      - standardConcept

    properties:
      conceptId:
        description: id of the concept
        type: integer
        format: int64
      conceptName:
        description: name of concept
        type: string
      domainId:
        description: domain of concept
        type: string
      vocabularyId:
        description: vocabulary of concept
        type: string
      conceptCode:
        description: original vocab code of concept
        type: string
      conceptClassId:
        description: class of concept
        type: string
      standardConcept:
        description: standard concept value 1 char
        type: string
      countValue:
        description: est count in the cdr
        type: integer
        format: int64
      prevalence:
        description: prevalence among participants percent count divided num participants
        type: number
        format: float

  ConceptListResponse:
    type: object
    required:
      - items
    properties:
      items:
        type: "array"
        items:
          $ref: "#/definitions/Concept"

  QuestionConcept:
    type: object
    required:
      - conceptId
      - conceptName
      - domainId
      - conceptCode
      - standardConcept

    properties:
      conceptId:
        description: id of the concept
        type: integer
        format: int64
      conceptName:
        description: name of concept
        type: string
      domainId:
        description: domain of concept
        type: string
      conceptCode:
        description: original vocab code of concept
        type: string
      countValue:
        description: est count in the cdr
        type: integer
        format: int64
      prevalence:
        description: prevalence among participants percent count divided num participants
        type: number
        format: float
      analyses:
        description: analyses with answer results to questions
        type: array
        items:
          $ref: "#/definitions/Analysis"

  QuestionConceptListResponse:
    type: object
    required:
      - items
    properties:
      survey:
        $ref: "#/definitions/DbDomain"
      items:
        type: array
        items:
          $ref: "#/definitions/QuestionConcept"





  AnalysisResult:
    type: object
    required:
      - analysisId

    properties:
      id:
        description: pk id for jpa code to work
        type: integer
        format: int64
      analysisId:
        description: id analysis
        type: integer
        format: int64
      countValue:
        description: count
        type: integer
        format: int64
      stratum1:
        description: stratum 1
        type: string
      stratum1Name:
        description:  usually concept name corresponding to stratum
        type: string
      stratum2:
        description: stratum 2
        type: string
      stratum2Name:
        description:  usually concept name corresponding to stratum
        type: string
      stratum3:
        description: stratum 3
        type: string
      stratum3Name:
        description:  usually concept name corresponding to stratum
        type: string
      stratum4:
        description: stratum 4
        type: string
      stratum4Name:
        description:  usually concept name corresponding to stratum
        type: string
      stratum5:
        description: stratum 5
        type: string
      stratum5Name:
        description:  usually concept name corresponding to stratum
        type: string

  AnalysisResultListResponse:
    type: object
    required:
      - items
    properties:
      items:
        type: "array"
        items:
          $ref: "#/definitions/AnalysisResult"

  AchillesResult:
    type: object
    required:
      - analysisId

    properties:
      id:
        description: pk id for jpa code to work
        type: integer
        format: int64
      analysisId:
        description: id analysis
        type: integer
        format: int64
      stratum1:
        description: stratum 1
        type: string
      stratum2:
        description: stratum 2
        type: string
      stratum3:
        description: stratum 3
        type: string
      stratum4:
        description: stratum 4
        type: string
      stratum5:
        description: stratum 5
        type: string
      countValue:
        description: count
        type: integer
        format: int64

  AchillesResultListResponse:
    type: object
    required:
      - items
    properties:
      items:
        type: "array"
        items:
          $ref: "#/definitions/AchillesResult"



  Analysis:
    type: object
    required:
      - analysisId
    properties:
      analysisId:
        description: id analysis
        type: integer
        format: int64
      analysisName:
        description:  analysis name
        type: string
      stratum1Name:
        description:  usually concept name corresponding to stratum
        type: string
      stratum2Name:
        description:  usually concept name corresponding to stratum
        type: string
      stratum3Name:
        description:  usually concept name corresponding to stratum
        type: string
      stratum4Name:
        description:  usually concept name corresponding to stratum
        type: string
      stratum5Name:
        description:  usually concept name corresponding to stratum
        type: string
      chartType:
        description:  chart type to display for this analysis column pie box
        type: string
      dataType:
        description:  data type of this analysis count or distribution
        type: string
      results:
        description: count results
        type: array
        items:
          $ref: "#/definitions/AchillesResult"
      stratum1:
        description: stratum 1
        type: string
      stratum2:
        description: stratum 2
        type: string
      stratum3:
        description: stratum 3
        type: string
      stratum4:
        description: stratum 4
        type: string
      stratum5:
        description: stratum 5
        type: string

  AnalysisListResponse:
    type: object
    required:
      - items
    properties:
      items:
        type: "array"
        items:
          $ref: "#/definitions/Analysis"

  DbDomain:
    type: object
    required:
      - domainId
    properties:
      domainId:
        description: domain id
        type: string
      domainDisplay:
        description:  web display name
        type: string
      domainDesc:
        description:  full desc text
        type: string
      dbType:
        description:  parent id
        type: string
      domainRoute:
        description:  route
        type: string
      conceptId:
        description: concept id
        type: integer
        format: int64
      numParticipants:
        description: number of respondents
        type: integer
        format: int64


  DbDomainListResponse:
    type: object
    required:
      - items
    properties:
      items:
        type: "array"
        items:
          $ref: "#/definitions/DbDomain"




